### ISSUE TITLE
Support for RTS5179 or RTS5170

### ISSUE THREAD

**Issue by loctran016** [cholonam/Sinetek-rtsx#13]
Excuse me, does your kext work on RTS5179 or RTS5170. I'm using the DELL INSPIRON 3421 (Ivy Bridge CPU) with one of these SD card reader: RTS5179 or RTS5170 (sorry that I can't find what I'm exactly using but I get this information from the [DELL Drivers for my card reader](https://www.dell.com/support/home/en-bo/drivers/driversdetails?driverid=r1fpk&oscode=wt64a&productcode=inspiron-14-3421). I've tried this but it seem doesn't work at all. Can you help me with this, thanks.
Here is my DELL INSPIRON 3421 specs (by AIDA64 Engineering):
[Report.txt](https://github.com/cholonam/Sinetek-rtsx/files/5057359/Report.txt)

**Comment by cholonam** [comment]
Hello, only RTS525A is tested/supported. Other models may or may not work, but are not tested at all. In the case of RTS51xx, it seems it is quite a different model, so most likely it will not work with this driver.

**Comment by loctran016** [comment]
Thanks for letting me know.
