### ISSUE TITLE
Using it on a pci10ec,5287; working as documented but not waking from sleep.

### ISSUE THREAD

**Issue by diepeterpan** [cholonam/Sinetek-rtsx#19]
Using the kext on a pci10ec,5287. (Acer Aspire 5 from 2018); working as documented but not waking from sleep.

Just in case you want to add it to the list of devices it is working; don't expect the sleep to be fixed.

I did add the rtsx_sleep_wake_delay_ms=1000 and update to 2.4 but it isn't waking ;-)

I will try some different timings; if it wakes I will revert to this issue entry.

**Comment by cholonam** [comment]
Thanks. I'll add it to the readme. Are you using the mimic_linux flag?
