### ISSUE TITLE
Card reader native information

### ISSUE THREAD

**Issue by TzeKitKwok** [cholonam/Sinetek-rtsx#20]
About local-system report How to display card reader information, I want to implement it, how to do？
<img width="895" alt="截屏2021-02-10 下午10 48 47" src="https://user-images.githubusercontent.com/42382226/107527445-c74efe80-6bf3-11eb-9b8b-4c60adef16f7.png">
The content of the picture is that this computer does not contain any Apple internal memory card

**Comment by cholonam** [comment]
My guess is there may be some API for that in IOKit, but I have not looked into it.
