### ISSUE TITLE
Sinetek reader as a card reader

### ISSUE THREAD

**Issue by seungjunProgramming** [cholonam/Sinetek-rtsx#24]
At Apple -> System Information -> Card reader, It shows that there is no card reader available.
Will there be a patch to fix this???
(Since injected sd cards are now shown up as a sd card at finder.)

If you do not have any plan to fix it, where document can I look up for those kind of stuffs???
(Maybe IOKit has it???)

I am willing to contribute if you don't have a plan to fix it!
(I am not that good at programming, but I will do my best)

**Comment by cholonam** [comment]
Hello @seungjunProgramming, thanks for the pull request.

Regarding this, please refer to issue #20. My guess is there must be some properties that must be set on the IOServive, or some IOKit API call that has to be made, but fixing this would require at least several hours of troubleshooting (in the best case, some days or just not possible in the worst case). Just too much work for so little value...

**Comment by brendonjkding** [comment]
![image](https://user-images.githubusercontent.com/47965860/114271336-6b61f400-9a43-11eb-8619-c0be50686914.png)

Managed to get the card reader recognized. However, some other devices also get the property I set and recognized as a card reader. Does anyone have an idea?

(Note that Another userspace patch is not included in the picture. )

**Comment by seungjunProgramming** [comment]
@brendonjkding Can you upload the full code plz???
