### ISSUE TITLE
Why buildnumber as versionnumber?

### ISSUE THREAD

**Issue by ProfDrLuigi** [cholonam/Sinetek-rtsx#26]
Hi cholonam.

Is it possible to put the Versionnumber instead of Buildnumber into the Info.plist? Normaly that is the regular way.

![grafik](https://user-images.githubusercontent.com/45099401/110361173-f19faa80-803f-11eb-98ab-c9bdbadad40a.png)

I´m the Author of the "Kext Updater" and it couldn´t detect it correctly because 9 is higher than 2.x and the users always get the message that the kext is the latest version and it is not.

**Comment by cholonam** [comment]
Hi, my understanding was that the build number is just an integer increased on every build publicly released, and the version is the semantic version (x.y.z), but I may be wrong.. are you recommending to use the semantic version also as the build number? It that's the common practice I'm ok with that.

I'll look into it as soon as I have some time. If you are familiar with the common practice and can explain it to me here, I'd appreciate it :)

**Comment by ProfDrLuigi** [comment]
Yes, x.y.z is common usual. ;)  Simply put the $(MODULE_VERSION) String as showed below: 

![grafik](https://user-images.githubusercontent.com/45099401/110432108-ff404900-80ae-11eb-80cc-4c264a310b38.png)

![grafik](https://user-images.githubusercontent.com/45099401/110432142-0a937480-80af-11eb-8608-c3b98384bd53.png)

**Comment by cholonam** [comment]
Looks good, thanks. I bumped all three versions to 9.0.0, so that kext updaters see the version increase from both 9 and 2.5. Your updater may not detect this as a new version (if it considers 9 == 9.0.0), but there are no code changes anyway, so no need to update this time. Next version upgrade, it should pick it up. Correct me if I'm wrong.
