### ISSUE TITLE
rtsx_sleep_wake_delay_ms=1000 works on pci10ec,522a 

### ISSUE THREAD

**Issue by the-eric-kwok** [cholonam/Sinetek-rtsx#27]
As the title said, the argument `rtsx_sleep_wake_delay_ms=1000` makes my RTS522A work properly!

**Comment by cholonam** [comment]
Thanks for the update. Do you mean sleep/wake is working properly? According to the README.md, this chip was having random wake ups. Can you confirm this problem is gone by using this argument? I'd appreciate it if you can comment a bit more on what exactly the problem was before adding it (where you having random wakes? no random wakes but card not working after wake?).

Thanks again.

**Comment by the-eric-kwok** [comment]
By "works properly" I mean the reader detected and read my card properly after sleep and wake. And for the random wake up issue I haven't tested it yet.

**Comment by cholonam** [comment]
If you could test wether sleep works (no random wakes and card detected after wake), that'd be very helpful. Then I'll update the README with your results. Thanks.

**Comment by the-eric-kwok** [comment]
After a 40-min sleep I didn't see any randomly waking up. I'll test this at night and see if any issue occurs. 
And the card is detected and read properly after 40-minute sleep.

**Comment by the-eric-kwok** [comment]
I can confirm that there is no randomly waking up issue on my side.

**Comment by cholonam** [comment]
README updated. Thank you!

**Comment by the-eric-kwok** [comment]
Should add the boot-arg `rtsx_sleep_wake_delay_ms=1000`, otherwise it won't respond after sleep.

**Comment by cholonam** [comment]
You are right. I forgot to add that. Fixed now, thanks.

**Comment by NanoSector** [comment]
Sorry for the necrobump, but I wanted to share my two cents in this. On an Elitebook 840 G2 (RTS5227) with version 9.0 on Big Sur 11.5.2, with or without the parameter sleep works absolutely fine.

The difference here is in that I need to re-attach the SD card without the parameter, where it'll appear in Finder after a little while with it.

Overall I'm not seeing any issues with this kext, thanks!
