### ISSUE TITLE
Files missing after finish copying to Micro SDXC card

### ISSUE THREAD

**Issue by celerond256** [cholonam/Sinetek-rtsx#31]
Hello @cholonam, 

After loading kext via opencore, Micro SDXC card recognized successfully. But, after i copied some files into it, the files was missing (folders are still there).
I only use boot-args rtsx_sleep_wake_delay_ms=1000.

My Device are:
Lenovo Thinkpad X260
SD card reader: RTS522A
OS: catalina 10.15.7
Bootloader : OpenCore 0.7.0 

What setting I’m missing?

thanks.

**Comment by cholonam** [comment]
Hi @celerond256,

Your boot args seem fine. At least that's what's working for others, as per the README file (which I update according to comments I get). I do not have this chip, so I cannot test it, nor can I guarantee it will work.

In any case, it seems very weird to me that only folders are being copied. If the kext wasn't working property, it makes more sense that you'd get a corrupt filesystem or nothing copied at all.

Please, first of all, check that the file system is not corrupt. Try a few more times, after format, a different card, etc. **Do not use this kext in production unless you are really sure it works with your chip.** If I remember correctly, some others with Thinkpads have reported problems, so it may be that you are just out of luck...

Please let me know if you get some positive results. Closing for now.
