### ISSUE TITLE
Which version of Card Reader is this ? 

### ISSUE THREAD

**Issue by THOMASVGTR** [cholonam/Sinetek-rtsx#34]
I am confused about which type of Card Reader it is. Could someone please explain !? Though sdcards can fully read, write data with this kext but SD Cards getting unmounted & unreadable after laptop waking from sleep.

I am attaching a picture bellow, (Google Drive link). 

https://drive.google.com/file/d/1jpE54vC72NP42v6oRykwis4U4TjvAnC0/view?usp=sharing

**Comment by cholonam** [comment]
Please check the README for chips known to work and issues found for each one. Also, you may have better luck with this https://github.com/cholonam/Sinetek-rtsx/issues/33
