### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by blackflag161** [cholonam/Sinetek-rtsx#5]
Whenever a I pull a file (for example an image file in RAW or jpeg) from a micro SD card, the images come out corrupted with random color patterns overlaid on top. This happens regardless of the card that I use.

**Comment by cholonam** [comment]
Hello @blackflag161. I need for information. What is your exact chip number/version? Which card capacity/speed? Can you upload the logs generated by the debug version of the kext? If you were getting corrupted data you should not be able to read the directory structure either. In any case, I have not tested micro-SD, so it may not be working.. Hopefuy I can tell you more once I see the logs.

**Comment by blackflag161** [comment]
<img width="1371" alt="Screenshot 2020-04-24 at 00 52 49" src="https://user-images.githubusercontent.com/61255867/80158268-5ee15300-85c8-11ea-9b1a-38dc6d8aaebe.png">
This is what I could find out about the chip. SD Card is a Sandisk Extreme Pro 32GB micro SDHC U3 card. Got two of them, both generate the same result. Yeah it's weird. Folder structure is fine, I even appear to be able to format the card. Looks like I can even copy stuff back and forth without it getting corrupted. Whatever comes from a camera is though. Not sure if I managed to pull the correct logs, hope it helps.
<img width="1241" alt="grafik" src="https://user-images.githubusercontent.com/61255867/80159051-5c7ff880-85ca-11ea-91da-238b7ba24e6f.png">

<img width="1161" alt="Screenshot 2020-04-24 at 01 14 40" src="https://user-images.githubusercontent.com/61255867/80158560-15453800-85c9-11ea-987a-02706865de17.png">

**Comment by cholonam** [comment]
Thank you @blackflag161. I think I was able to reproduce and solve this problem. This was affecting only large data reads/writes and that's why the directory structure could be read without problem, but large pictures were being read corrupted. I uploaded version 2.2 which should have solved this problem.

**Comment by blackflag161** [comment]
> Thank you @blackflag161. I think I was able to reproduce and solve this problem. This was affecting only large data reads/writes and that's why the directory structure could be read without problem, but large pictures were being read corrupted. I uploaded version 2.2 which should have solved this problem.

Thank you very much, you are a legend! It is working now. Speeds aren't anything to write home about, but we knew that since the original sinetek kext, so no problem here :)
