### ISSUE TITLE
Not working on Mojave?

### ISSUE THREAD

**Issue by joshuaseltzer** [cholonam/Sinetek-rtsx#6]
Hi there.  First off, thank you for picking up this project and improving it!

I tried installing the latest Release (2.1.0) on my machine running Mojave.  It's a T440s, which has been confirmed to work from others running Catalina.  However, I'm still on Mojave and it's not working.

I even tried compiling the latest from source and it's still not working properly.  Are there any specific build instructions to build the release kext?

I've tried both with Clover injection, as well as in /Library/Extensions.  When I did /L/E and ran kextcache, I saw these errors:
`kxld[com.sinet3k.Sinetek-rtsx]: The super class vtable 'vtable for IOService' for vtable 'vtable for Sinetek_rtsx' is out of date. Make sure your kext has been built against the correct headers.`

`kxld[com.sinet3k.Sinetek-rtsx]: The super class vtable 'vtable for IOBlockStorageDevice' for vtable 'vtable for SDDisk' is out of date. Make sure your kext has been built against the correct headers.`

`Link failed (error code 5).`

`Prelink failed for com.sinet3k.Sinetek-rtsx; omitting from prelinked kernel.`

Any thoughts?

**Comment by cholonam** [comment]
This weekend I'll upload a release that should load in Mojave too. Meanwhile, if you can build the current master branch, that should work too, since the change is already in master.

**Comment by joshuaseltzer** [comment]
I tried building the latest master but it also wasn’t working. Are there any specific build instructions? Will the kext work properly with Clover kext injection?

**Comment by cholonam** [comment]
Hello @joshuaseltzer. I uploaded the new release, so you can try that.

There are no special build instructions. Just open the project with Xcode and build the release or debug version (there should be no warnings if you use the latest version).

The kext should work with Clover injection (I haven't tried L/E), but I recommend you load it manually and check the logs until you get it working and stable enough.

**Comment by joshuaseltzer** [comment]
Interesting even this new release isn't working on my hardware.  I wonder if there's something wrong with my config, or my card reader is a different model than what is supported.  I'm not entirely sure to be honest.

I'll circle back and try again when I eventually move to Catalina.

EDIT: This is my device identifier: 0x522710EC.  Other people over on TonyMacx86 have reported your updated kext is working on the Lenovo T440s (which all should have this ID, I would think).  So maybe there's still an issue getting it loading on Mojave?

**Comment by joshuaseltzer** [comment]
Noticed you uploaded a compiled version using the older SDK to the releases.  This one is now working! This explains why I couldn't build it myself: I was likely using the 10.15 SDK (even though I'm on 10.14).

Thank you for your fixes!
