### ISSUE TITLE
Wake

### ISSUE THREAD

**Issue by rboldini** [cholonam/Sinetek-rtsx#7]
Model: pci10ec,5227
System version: 10.15.4
Kext’s version: 2.1 Debug
Status: workin

Issue: after wake disk is unmounted, kext is loaded and recognize the card but is not able to mount it again

Putting off and then Inserting card again the system recognize it as corrupted for the first time, next times system says nothing about it.
restart the system is the only way to make it working again 

Edit: 
Test2
In bios setting founded option for Card Reader power saving set to false, switched it to true , that allowed the system to recognize cards as corrupted after wake every time I insert in again.

Edit2:
Test3
Having doubt about my PM, I’ve tried to do the same thing with an USB stick, sleep unmount the stick but reinsert it make it working again.
Conclusion issue is kext PM related.

Sorry for poor English

**Comment by cholonam** [comment]
Thank you for your feedback @xWeapon. This kext only supports model 525A, but I'm glad the kext is working for you at least without sleep/wake. I encourage you to look at the Linux sourcecode and see if your chip needs some initialization that's not being made after wake. I'll be happy to accept your pull request if you find the problem.
